{
 "title": "Microservices .NET Metrics from Otel Collector",
 "tags": [
  "aspnetcore",
  "dotnet",
  "opentelemetry",
  "otel"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "app_name",
    "label": "Application Name",
    "query": {
     "query": "label_values(custom_metric_microservices_dotnet_app_info, app_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(custom_metric_microservices_dotnet_request_total{app_name=\"$app_name\", path!~\"/swagger.*\"})"
    }
   ]
  },
  {
   "title": "Requests Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(path) (custom_metric_microservices_dotnet_requests_duration_seconds_count{app_name=\"$app_name\", path!~\"/swagger.*\"})",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Requests Average Duration",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "custom_metric_microservices_dotnet_requests_duration_seconds_sum{app_name=\"$app_name\", path!~\"/swagger.*\"} / custom_metric_microservices_dotnet_requests_duration_seconds_count{app_name=\"$app_name\", path!~\"/swagger.*\"}",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Total Exceptions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "custom_metric_microservices_dotnet_exceptions_total{app_name=\"$app_name\"}"
    }
   ]
  },
  {
   "title": "Log of All App",
   "type": "logs",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 6 },
   "targets": [
    {
     "expr": "{app_name=\"$app_name\"} != \"swagger\""
    }
   ]
  }
 ]
}