apiVersion: 1

datasources:
- uid: prometheus
  orgId: 1
  name: Prometheus
  type: prometheus
  typeName: Prometheus
  access: proxy
  url: http://prometheus:9090
  basicAuth: false
  isDefault: true
  version: 1
  jsonData:
    exemplarTraceIdDestinations:
      - datasourceUid: jaeger
        name: trace_id
  readOnly: false
  editable: true

- uid: jaeger
  name: Jaeger
  type: jaeger
  url: http://jaeger:16686
  access: proxy
  version: 1
  apiVersion: 1
  isDefault: false
  jsonData:
    nodeGraph:
      enabled: true
    lokiSearch:
      datasourceUid: loki
    tracesToLogs:
      datasourceUid: loki
      filterBySpanID: false
      filterByTraceID: true
      mapTagNamesEnabled: false
      tags: 
        - app_name
  readOnly: false
  editable: true

- uid: loki
  orgId: 1
  name: Loki
  type: loki
  typeName: Loki
  access: proxy
  url: http://loki:3100
  basicAuth: false
  isDefault: false
  version: 1
  jsonData:
    derivedFields:
      - datasourceUid: 'jaeger'
        matcherRegex: '"traceid":\s*"([a-f0-9]+)"'
        name: TraceID
        url: '$${__value.raw}'
        urlDisplayLabel: 'Jaeger'
  readOnly: false
  editable: true